[package]
name = "nano"
version = "0.1.0"
edition = "2021"
description = "Discord bot to authenticate and de-anonymise users"
homepage = "https://github.com/supleed2/nanobot"
repository = "https://github.com/supleed2/nanobot"
license = "ISC"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
axum = "0.7.4"
indoc = "2.0.4"
poise = "0.6.1"
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.195", features = ["derive"] }
shuttle-runtime = { version = "0.36.0", default-features = false }
shuttle-secrets = "0.36.0"
shuttle-shared-db = { version = "0.36.0", features = ["postgres"] }
sqlx = { version = "0.7.3", features = [
	"macros",
	"postgres",
	"runtime-tokio-native-tls",
] }
tokio = "1.35.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
url = "2.5.0"
